### ISSUE TITLE
nginx is not starting 

### ISSUE THREAD

**Issue by prashantkumar112** [aschmelyun/docker-compose-wordpress#3]
Running below command give me below status of the containers and nginx is not up
$docker-compose ps
Name               Command               State                           Ports                       
-----------------------------------------------------------------------------------------------------
mysql   docker-entrypoint.sh mysqld      Up       0.0.0.0:3306->3306/tcp,:::3306->3306/tcp, 33060/tcp
**nginx   /docker-entrypoint.sh ngin ...   Exit 1**                                                      
php     docker-php-entrypoint php-fpm    Up       9000/tcp

**Comment by BaronVonPerko** [comment]
I had an issue where my nginx would not start.  It was due to me forgetting to generate the SSL certs.  Check out [this readme](https://github.com/aschmelyun/docker-compose-wordpress/blob/main/nginx/certs/README.md)

**Comment by prashantkumar112** [comment]
@BaronVonPerko Thanks ...it worked.....nginx is up and running...but now I am getting 403 forbidden error....any idea about that?

**Comment by prashantkumar112** [comment]
@BaronVonPerko  Thanks ....It woked.
